### ISSUE TITLE
Create sub-organizations

### ISSUE THREAD

**Issue by martinvanzijl** [martinvanzijl/org-chart-maker#48]
Allow making a sub-organization box that you can click on to view that part of the organization. (Similar to making a hyperlink to another diagram for a box in Visio.)

**Comment by martinvanzijl** [comment]
@cvz04 Could you please provide feedback on the following:

- When exporting to a CSV file, how should the sub-org’s be represented?
- Should relationships be allowed to/from sub-orgs just as with persons?

**Comment by cvz04** [comment]
> @cvz04 Could you please provide feedback on the following:
> 
> * When exporting to a CSV file, how should the sub-org’s be represented?

When exporting persons, you only need to show the Department (sub-org) the person belongs to.
Ideally, the Department property of a person should be identical to its sub-org.

One option is to create the sub-org structure (Department structure) first.
After that, a person can only be assigned to an existing sub-org / department.


> * Should relationships be allowed to/from sub-orgs just as with persons?

Yes, sub-orgs can belong to a parent and also have child sub-orgs of its own.
A direct relationship between a sub-org and a person is not allowed.

A sub-org must always have one (and only one) org diagram associated with it.

**Comment by martinvanzijl** [comment]
For exporting to CSV, I plan the following

[sub-org-csv-example.csv](https://github.com/martinvanzijl/org-chart-maker/files/12656600/sub-org-csv-example.csv)

**Comment by cvz04** [comment]
- [ ] After implementation of sub-org, please remove Department input from Person 

- [ ] Remove "Filter by Dept" feature
